name: Update recent activity

on:
  schedule:
    - cron: '* */3 * * *' # Update every 3 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update recent actvity

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
